import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../main.dart';
import '../widgets/printer_card.dart';
class PrintersScreen extends StatefulWidget { const PrintersScreen({super.key}); @override State<PrintersScreen> createState() => _PrintersScreenState(); }
class _PrintersScreenState extends State<PrintersScreen> { final ip = TextEditingController(); bool loading = false; @override Widget build(BuildContext context) { final state = context.watch<AppState>(); return Padding(padding: const EdgeInsets.all(32), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('FLEET / PRINTERS', style: Theme.of(context).textTheme.labelSmall?.copyWith(color: const Color(0xFF00D97E), letterSpacing: 1.5)), const SizedBox(height: 8), Text('Printers', style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w800))]), Wrap(spacing: 8, children: [OutlinedButton.icon(onPressed: loading ? null : _discover, icon: const Icon(Icons.radar), label: const Text('Discover')), OutlinedButton.icon(onPressed: _manual, icon: const Icon(Icons.add), label: const Text('Manual IP'))])]), const SizedBox(height: 24), Expanded(child: state.printers.isEmpty ? const Center(child: Text('No printers discovered.')) : ListView.builder(itemCount: state.printers.length, itemBuilder: (_, index) => PrinterCard(state.printers[index]))) ])); }
  Future<void> _discover() async { setState(() => loading = true); await context.read<AppState>().discoverPrinters(); if (mounted) setState(() => loading = false); }
  Future<void> _manual() async { final app = context.read<AppState>(); final value = await showDialog<String>(context: context, builder: (_) => AlertDialog(title: const Text('Add printer by IP'), content: TextField(controller: ip, autofocus: true, decoration: const InputDecoration(hintText: '192.168.1.42')), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(context, ip.text), child: const Text('Add'))])); if (!mounted) return; if (value != null && value.trim().isNotEmpty) await app.addManualPrinter(value.trim()); }
}
