import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:http/http.dart' as http;

class IppService {
  final http.Client client;
  IppService({http.Client? client}) : client = client ?? http.Client();
  Future<Map<String, String>> getPrinterAttributes(Uri ippUri) async { final response = await client.post(_httpUri(ippUri), headers: {'Content-Type': 'application/ipp', 'Accept': 'application/ipp'}, body: _request(0x000B, ippUri, includeDocument: false)); _ensureOk(response); return _parseAttributes(response.bodyBytes); }
  Future<void> printJob(Uri ippUri, File file, String filename) async { final bytes = await file.readAsBytes(); final response = await client.post(_httpUri(ippUri), headers: {'Content-Type': _mime(filename), 'Accept': 'application/ipp'}, body: _request(0x0002, ippUri, includeDocument: true, document: bytes, documentName: filename)); _ensureOk(response); }
  Uri _httpUri(Uri uri) => uri.scheme == 'ipp' ? uri.replace(scheme: 'http') : uri;
  Uint8List _request(int operation, Uri printerUri, {required bool includeDocument, Uint8List? document, String? documentName}) { final out = BytesBuilder(); void u8(int value) => out.addByte(value); void u16(int value) { u8(value >> 8); u8(value); } void u32(int value) { u8(value >> 24); u8(value >> 16); u8(value >> 8); u8(value); } void text(String value) => out.add(utf8.encode(value)); void attr(int tag, String name, String value, {int valueTag = 0x41}) { u8(valueTag); u16(name.length); text(name); u16(value.length); text(value); } u8(2); u8(0); u16(operation); u32(DateTime.now().millisecondsSinceEpoch & 0x7fffffff); u8(1); attr(0x47, 'attributes-charset', 'utf-8', valueTag: 0x47); attr(0x48, 'attributes-natural-language', 'en', valueTag: 0x48); attr(0x45, 'printer-uri', printerUri.toString(), valueTag: 0x45); if (operation == 0x0002) { attr(0x42, 'requesting-user-name', Platform.localHostname, valueTag: 0x42); attr(0x49, 'job-name', documentName ?? 'PrintBridge job', valueTag: 0x49); attr(0x49, 'document-format', _documentFormat(documentName ?? ''), valueTag: 0x49); u8(3); out.add(document ?? Uint8List(0)); } else { u8(3); } return out.toBytes(); }
  String _documentFormat(String filename) { final lower = filename.toLowerCase(); if (lower.endsWith('.pdf')) return 'application/pdf'; if (lower.endsWith('.png')) return 'image/png'; if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg'; return 'application/octet-stream'; }
  Map<String, String> _parseAttributes(List<int> bytes) { final result = <String, String>{}; if (bytes.length < 8) return result; var offset = 8; String? name; while (offset < bytes.length) { final tag = bytes[offset++]; if (tag == 0x03 || tag == 0x04 || tag == 0x05) { name = null; continue; } if (offset + 4 > bytes.length) break; final nameLength = (bytes[offset] << 8) | bytes[offset + 1]; offset += 2; if (offset + nameLength + 2 > bytes.length) break; if (nameLength > 0) name = utf8.decode(bytes.sublist(offset, offset + nameLength), allowMalformed: true); offset += nameLength; final valueLength = (bytes[offset] << 8) | bytes[offset + 1]; offset += 2; if (offset + valueLength > bytes.length) break; final value = utf8.decode(bytes.sublist(offset, offset + valueLength), allowMalformed: true); offset += valueLength; if (name != null) result[name] = value; } return result; }
  void _ensureOk(http.Response response) { if (response.statusCode < 200 || response.statusCode >= 300) throw HttpException('IPP request failed with HTTP ${response.statusCode}'); if (response.bodyBytes.length >= 2 && response.bodyBytes[0] != 2) throw const FormatException('Unsupported IPP response version'); }
  String _mime(String filename) { final lower = filename.toLowerCase(); if (lower.endsWith('.pdf')) return 'application/pdf'; if (lower.endsWith('.png')) return 'image/png'; if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg'; return 'application/octet-stream'; }
}
